version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/aws_devops_nodejs

permissions:
  - object: / 
    pattern: "**"
    owner: root
    group: root
hooks: 
  BeforeInstall:
  - location: scripts/remove_backend_node
    timeout: 60
    runas: root
  ApplicationStart:
  - location: scripts/restart_backend
    timeout: 60
    runas: root
